name: mw-cleanup-assistant

services:
  web-server:
    build:
      #Use the repository directory as the main context
      context: mw-cleanup-assistant
      #Use the dockerfile provided in the repository
      dockerfile: deployment/docker-gunicorn/Dockerfile
    ports:
      #Map the server to host port 8080
      - 127.0.0.1:8080:80
    volumes:
      #Create a volume for the database
      - database:/var/lib/mw-cleanup-assistant
      #Mount the local configuration file
      - ./config.toml:/mw-cleanup-assistant/config.toml
    logging:
      #The local logging driver provides log rotation and limits space usage by default
      driver: local
    #Enable the init process so child processes can be reaped
    init: true

volumes:
  database:
