#This is an apache configuration file with the absolute minimum settings to make the server
#application work properly. Depending on your system configuration and needs you might need to add
#more settings.
#Notes:
# - Replace [path_to_repo] with the fully qualified path to the repository
# - Replace [path_to_python] with the fully qualified path to the python executable or virtual
#   environment.

<VirtualHost *:80>
  PassengerAppRoot [path_to_repo]
  PassengerPython [path_to_python]
</VirtualHost>
