#Sample configuration file. All commented configurations contain their default values where
#applicable. Uncomment and edit to change them.

[sqlite3]
#path = 'db.sqlite3'  #Default sqlite3 database file (consider moving to /var or similar)

[mediawiki_server]
#api =                #A server URL must be provided, like: 'https://www.example.com/w/api.php'
#cors_proxy = false   #Whether to enable the Cross Origin Resource Sharing proxy

[perceptual_hashing]
#resolution_limit = 10000000   #Downscale images to this if larger before hashing (10000000 = 10MP)
#image_magick_max_mem = ''     #Maximum amount of RAM allowed to ImageMagick (example: '256MiB')

[reverse_proxy]
# enabled = false     #Enable if this application is exposed by a web server in reverse_proxy mode
