name: mw-unused-image-finder

services:
  web-server:
    build:
      #Use the dockerfile provided in the repo
      dockerfile: mw-unused-image-finder/docker/Dockerfile
      args:
        #Set the relative path to the repo so sources can be found
        - SRC_DIR=mw-unused-image-finder
        #Set the path to the configuration file
        - CONFIG_FILE=config.toml
    ports:
      #Map the server to host port 8080
      - 127.0.0.1:8080:80
    volumes:
      #Create a volume for the database
      - database:/var/lib/mw-unused-image-finder
    logging:
      #The local logging driver provides log rotation and limits space usage by default
      driver: local
    #Enable the init process so child processes can be reaped
    init: true

volumes:
  database:
